### ISSUE TITLE
No task data for weekends.

### ISSUE THREAD

**Issue by misoramen** [badboy/teuxdeux#2]
I've noticed the API does not return any data for tasks that are on Saturdays or Sundays.

**Comment by badboy** [comment]
Will look into it.

**Comment by badboy** [comment]
Both the API and my client implementation works as expected.

By default `TeuxDeux::Client#todos` (and the API endpoint) returns your todos for the current work days (that are 5, monday-friday)

Cited from http://teuxdeux.com/faq under _Can we have a view with 7 days instead of 5?_

> Your tasks for the weekend should generally only be things like: "Drink Lemonade in a Hammock" or "Take 3 Naps" or "Hit the Beach".

However if you specify an offset with `since` you get everything from that day on:

```
client.todo since: "2012-12-21"
```

Closing as non-bug.
